/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loanassistant;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author K Yashwanth Reddy
 */
public class LoanAssistantProject extends javax.swing.JFrame {
   private boolean Computepayment;
   
    double loan;
    double interest;
    double month;
    double payment;
    double Monthlypayment;
    
    
    
   
    
   
    
    public LoanAssistantProject() {
        initComponents();
        xmonthlypaymentbutton.doClick();
        loananalysisbutton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        balancefeild = new javax.swing.JTextField();
        interestfeild = new javax.swing.JTextField();
        numberofpaymentfeild = new javax.swing.JTextField();
        monthlypaymentfeild = new javax.swing.JTextField();
        computebutton = new javax.swing.JButton();
        loananalysisbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        loananalysistext = new javax.swing.JTextArea();
        exitbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        xnumberofpaymentbutton = new javax.swing.JButton();
        xmonthlypaymentbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loan Assistant Project");
        setResizable(false);

        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Loan Balance");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Interest Rate");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Number of Payment ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Monthly Payment ");

        balancefeild.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        balancefeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balancefeildActionPerformed(evt);
            }
        });

        interestfeild.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        interestfeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestfeildActionPerformed(evt);
            }
        });

        numberofpaymentfeild.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numberofpaymentfeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberofpaymentfeildActionPerformed(evt);
            }
        });

        monthlypaymentfeild.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        computebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        computebutton.setText("Compute Monthly Payment");
        computebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computebuttonActionPerformed(evt);
            }
        });

        loananalysisbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loananalysisbutton.setText("New Loan Analysis");
        loananalysisbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loananalysisbuttonActionPerformed(evt);
            }
        });

        loananalysistext.setColumns(20);
        loananalysistext.setRows(5);
        jScrollPane1.setViewportView(loananalysistext);

        exitbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitbutton.setText("Exit");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Loan Analysis");

        xnumberofpaymentbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        xnumberofpaymentbutton.setText("X");
        xnumberofpaymentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xnumberofpaymentbuttonActionPerformed(evt);
            }
        });

        xmonthlypaymentbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        xmonthlypaymentbutton.setText("X");
        xmonthlypaymentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xmonthlypaymentbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(loananalysisbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitbutton)
                .addGap(146, 146, 146))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(173, 173, 173)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(interestfeild, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balancefeild, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(monthlypaymentfeild, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(xmonthlypaymentbutton))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(numberofpaymentfeild, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(74, 74, 74)
                                    .addComponent(xnumberofpaymentbutton)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(computebutton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(numberofpaymentfeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(xnumberofpaymentbutton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(balancefeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(interestfeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(jLabel3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(monthlypaymentfeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(xmonthlypaymentbutton))))
                        .addGap(46, 46, 46)
                        .addComponent(computebutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loananalysisbutton)
                            .addComponent(exitbutton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void balancefeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balancefeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balancefeildActionPerformed

    private void interestfeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestfeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interestfeildActionPerformed

    private void numberofpaymentfeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberofpaymentfeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberofpaymentfeildActionPerformed

    private void loananalysisbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loananalysisbuttonActionPerformed
        balancefeild.setText("");
        interestfeild.setText("");
        numberofpaymentfeild.setText("");
        loananalysistext.setText("");
        loananalysisbutton.setEnabled(false);
        computebutton.setEnabled(true);
        
    }//GEN-LAST:event_loananalysisbuttonActionPerformed

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
            System.exit(0);
    }//GEN-LAST:event_exitbuttonActionPerformed

    private void xmonthlypaymentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xmonthlypaymentbuttonActionPerformed
        Computepayment = false;
        xnumberofpaymentbutton.setVisible(true);
        xmonthlypaymentbutton.setVisible(false);
        monthlypaymentfeild.setEditable(false);
        monthlypaymentfeild.setBackground(Color.YELLOW);
        monthlypaymentfeild.setFocusable(false);
        numberofpaymentfeild.setEditable(true);
        numberofpaymentfeild.setBackground(Color.WHITE);
        numberofpaymentfeild.setFocusable(true);
        balancefeild.requestFocus();
        computebutton.setVisible(true);
    }//GEN-LAST:event_xmonthlypaymentbuttonActionPerformed

    private void xnumberofpaymentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xnumberofpaymentbuttonActionPerformed
        //Computepayment = true;  //computebutton
        xnumberofpaymentbutton.setVisible(false);
        xmonthlypaymentbutton.setVisible(true);
        monthlypaymentfeild.setEditable(true);
        monthlypaymentfeild.setBackground(Color.WHITE);
        monthlypaymentfeild.setFocusable(true);
        numberofpaymentfeild.setEditable(false);
        numberofpaymentfeild.setBackground(Color.YELLOW);
        numberofpaymentfeild.setFocusable(false);
        balancefeild.requestFocus();
        
        
        
    }//GEN-LAST:event_xnumberofpaymentbuttonActionPerformed

    private void computebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computebuttonActionPerformed
        String iMonthPayment=String.format(monthlypaymentfeild.getText());
        
       
        if(balancefeild.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "enter amount of balance " , "Loan System ",JOptionPane.INFORMATION_MESSAGE );
            
            
        }
        else{
            loan = Double.parseDouble(balancefeild.getText());
            String Balance=String.format(balancefeild.getText());
            
        }
        
        if(interestfeild.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "enter amount of interest" , "Loan System ",JOptionPane.INFORMATION_MESSAGE );
            
            
        }
        else{
            interest = Double.parseDouble(interestfeild.getText());
            String iInterest=String.format(interestfeild.getText());
            
        }
       
          if(numberofpaymentfeild.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Enter the Number of Payment feild:","Loan System ",JOptionPane.INFORMATION_MESSAGE);
            
        }
        else
        {
            month=Double.parseDouble(numberofpaymentfeild.getText());
            String iMonth=String.format(numberofpaymentfeild.getText());
        }
        
       /* if(numberofpaymentfeild.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, " enter amount of monthly payment " , "Loan System ",JOptionPane.INFORMATION_MESSAGE );
            
            
        }
        else{
            month = Double.parseDouble(numberofpaymentfeild.getText());
            String iMonth=String.format(numberofpaymentfeild.getText());
            
        }*/
        
        payment = loan +((loan*interest)/100);
        Monthlypayment= payment/month;
        String PayMonth=String.format("%.2f", Monthlypayment);
        monthlypaymentfeild.setText(PayMonth);
        loananalysistext.append("\t\n Loan Assistant Project:\n\n"+" Amount of Loan:\t $"+ loan + 
                "\n Number of Payment: \t  $"+ interest+
                "\n Monthly Payment:\t $"+ month +
                "\n Payment per Month:\t  $"+Monthlypayment+
                "\n Total Loan Paymrnt: \t $"+payment+
                "\n Thank you!!!");
        loananalysisbutton.setEnabled(true);
        computebutton.setEnabled(false);
                
                
        
                
        
        
        
    }//GEN-LAST:event_computebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanAssistantProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanAssistantProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanAssistantProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanAssistantProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanAssistantProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balancefeild;
    private javax.swing.JButton computebutton;
    private javax.swing.JButton exitbutton;
    private javax.swing.JTextField interestfeild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loananalysisbutton;
    private javax.swing.JTextArea loananalysistext;
    private javax.swing.JTextField monthlypaymentfeild;
    private javax.swing.JTextField numberofpaymentfeild;
    private javax.swing.JButton xmonthlypaymentbutton;
    private javax.swing.JButton xnumberofpaymentbutton;
    // End of variables declaration//GEN-END:variables
}
